### ISSUE TITLE
基金自动刷新失效

### ISSUE THREAD

**Issue by AnHyun** [Shenfq/fund-watch#1]
在fund watch页面跑了一段时间后，fund watch图标出现了一个时钟的图标，然后基金涨幅就不会刷新了

**Comment by Shenfq** [comment]
项目主要是用来写vscode插件练手的，推荐使用「韭菜盒子」，功能更全，迭代也很快。
https://marketplace.visualstudio.com/items?itemName=giscafer.leek-fund
